// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvhm9ZC2e_-o6KWSPqOlK7PxEhJoRucFk',
    appId: '1:945487010136:android:45be5f8f0faab7dc50ad2d',
    messagingSenderId: '945487010136',
    projectId: 'geyserswitch-bloc',
    databaseURL: 'https://geyserswitch-bloc-default-rtdb.firebaseio.com',
    storageBucket: 'geyserswitch-bloc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_6atWVa_Om_wQdc3gvhPObRPIfc3-nx0',
    appId: '1:945487010136:ios:167b7c5fb5d853fd50ad2d',
    messagingSenderId: '945487010136',
    projectId: 'geyserswitch-bloc',
    databaseURL: 'https://geyserswitch-bloc-default-rtdb.firebaseio.com',
    storageBucket: 'geyserswitch-bloc.appspot.com',
    iosBundleId: 'com.geyserswitch.gsOrange',
  );

//TODO:[IOS Firebase option settings not forgetting the android MessengerID Change]

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2m4T7ylElcXPbPS9YupoRFX2ebfjB7bI',
    appId: '1:945487010136:web:e8a4a59dc40813b550ad2d',
    messagingSenderId: '945487010136',
    projectId: 'geyserswitch-bloc',
    authDomain: 'geyserswitch-bloc.firebaseapp.com',
    databaseURL: 'https://geyserswitch-bloc-default-rtdb.firebaseio.com',
    storageBucket: 'geyserswitch-bloc.appspot.com',
    measurementId: 'G-KGZ1VBFRL0',
  );

}