import 'package:equatable/equatable.dart';

/// How the notification was delivered to the app.
enum NotificationSource {
  /// Received over BLE (local, real-time or buffered).
  ble,

  /// Received via FCM push (remote / WiFi path).
  remote,
}

/// Types of notification events generated by the firmware.
enum NotificationType {
  /// Geyser auto-OFF: temperature reached or exceeded max limit.
  maxTempOff(0x01, 'Max Temp Auto-Off'),

  /// Geyser auto-ON: temperature dropped to min limit (auto-reheat enabled).
  minTempOn(0x02, 'Auto-Reheat On'),

  /// Alert: temperature dropped to min limit (auto-reheat disabled).
  minTempAlert(0x03, 'Min Temp Alert'),

  /// Temperature sensor is unresponsive or disconnected.
  sensorFail(0x04, 'Sensor Offline'),

  /// Temperature sensor recovered after a failure.
  sensorRecover(0x05, 'Sensor Recovered'),

  /// Power switched off after the max continuous run time was reached.
  maxOnTimeout(0x06, 'Max Run Time Reached'),

  /// Unrecognised event code from firmware.
  unknown(0x00, 'Unknown Event');

  const NotificationType(this.code, this.label);

  /// The event type byte sent over BLE (matches firmware EVT_* constants).
  final int code;

  /// Human-readable label for settings UI.
  final String label;

  /// Resolve from the BLE event type byte.
  static NotificationType fromCode(int code) {
    return NotificationType.values.firstWhere(
      (e) => e.code == code,
      orElse: () => NotificationType.unknown,
    );
  }

  /// Only the types that correspond to real firmware events.
  static List<NotificationType> get settable =>
      values.where((t) => t != unknown).toList();
}

/// A single notification event from the geyser device.
///
/// Stored locally (SQLite/Drift) for up to 7 days, then synced to cloud.
class DeviceNotification extends Equatable {
  const DeviceNotification({
    this.id,
    required this.deviceId,
    required this.type,
    required this.temperature,
    required this.timestamp,
    this.dismissed = false,
    this.synced = false,
    this.source = NotificationSource.ble,
  });

  /// Auto-increment primary key (null for new records).
  final int? id;

  /// Canonical RTDB device ID (8-char hex) this event came from.
  final String deviceId;

  /// The type of event.
  final NotificationType type;

  /// Temperature in integer °C at the time of the event.
  final int temperature;

  /// When the event occurred (UTC).
  final DateTime timestamp;

  /// Whether the user has dismissed this from the notifications list.
  /// Dismissed notifications are still stored and synced.
  final bool dismissed;

  /// Whether this record has been pushed to cloud storage.
  final bool synced;

  /// How this notification was delivered.
  final NotificationSource source;

  /// Short title for the notification tile.
  String get title => type.label;

  /// Descriptive body text for the notification tile.
  String get body {
    switch (type) {
      case NotificationType.maxTempOff:
        return 'Geyser turned off — reached $temperature°C (max limit)';
      case NotificationType.minTempOn:
        return 'Geyser turned on — temp dropped to $temperature°C';
      case NotificationType.minTempAlert:
        return 'Temperature dropped to $temperature°C — auto-reheat is off';
      case NotificationType.sensorFail:
        return 'Temperature sensor is not responding — geyser runs normally';
      case NotificationType.sensorRecover:
        return 'Temperature sensor is back online ($temperature°C)';
      // Must stay in step with the FCM copy in functions/index.js —
      // the same event arrives by either path.
      case NotificationType.maxOnTimeout:
        return 'Geyser turned off — maximum run time reached';
      case NotificationType.unknown:
        return 'Unknown event at $temperature°C';
    }
  }

  @override
  List<Object?> get props => [
        id, deviceId, type, temperature, timestamp, dismissed, synced, source,
      ];
}
